# Generated by Django 3.2.8 on 2022-09-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengarsipanData', '0002_auto_20220918_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewProfil',
        ),
    ]
