# Generated by Django 3.2.8 on 2022-09-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengarsipanData', '0003_delete_viewprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fileInput'),
        ),
    ]
