# Generated by Django 3.2.8 on 2022-09-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengarsipanData', '0004_alter_input_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='image',
            field=models.FileField(upload_to='fileInput'),
        ),
    ]
