# Generated by Django 3.2.8 on 2022-09-21 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengarsipanData', '0005_alter_input_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileInput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengarsipanData.input')),
            ],
        ),
    ]
