# Generated by Django 3.2.8 on 2022-09-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengarsipanData', '0006_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profil',
        ),
    ]
