# Generated by Django 3.2.8 on 2022-09-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengarsipanData', '0008_alter_input_kategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='kategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pengarsipanData.kategori'),
        ),
    ]
