# Generated by Django 3.2.8 on 2022-09-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengarsipanData', '0010_alter_input_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
