# Generated by Django 3.2.8 on 2022-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='jabatan',
            field=models.CharField(max_length=20, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
