# Generated by Django 3.2.8 on 2022-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_biodata_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='jabatan',
            field=models.TextField(max_length=20, null=b'I01\n'),
        ),
    ]
