# Generated by Django 3.2.8 on 2022-09-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_biodata_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='email',
            field=models.CharField(max_length=50, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
