# Generated by Django 3.2.8 on 2022-09-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_biodata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.SET_NULL, to='user.biodata')),
            ],
        ),
    ]
