# Generated by Django 3.2.8 on 2022-09-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminUser',
        ),
    ]
