# Generated by Django 3.2.8 on 2022-09-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220918_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'ordering': ['-id']},
        ),
    ]
