# Generated by Django 3.2.8 on 2022-09-22 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_alter_biodata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='namabelakang',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='namadepan',
        ),
        migrations.AlterField(
            model_name='biodata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biodata', to=settings.AUTH_USER_MODEL),
        ),
    ]
